### ISSUE TITLE
function name conflict?

### ISSUE THREAD

**Issue by yongheekim-dev** [foldfelis/Terming.jl#32]
``` julia 
using GameDataManager
WARNING: both Terming and Base export "print"; uses of it in module GameDataManager must be qualified
WARNING: both Terming and Base export "join"; uses of it in module GameDataManager must be qualified
WARNING: both Terming and Base export "displaysize"; uses of it in module GameDataManager must be qualified
WARNING: both Terming and Base export "println"; uses of it in module GameDataManager must be qualified
WARNING: both Terming and Base export "write"; uses of it in module GameDataManager must be qualified
```

Exporting functions in Base would make many people scratch their heads, should use different name? or not export them?

**Comment by foldfelis** [comment]
Owing to the design, this issue can be solved by qualified the package name currently. For example: use `Terming.print()` instead of `print()`. This issue and design will be revised in **the next update***. 😺

**Comment by foldfelis** [comment]
After several times of discussion with @yuehhua  and @chengchingwen , the better way to solve this is simply not to export those functions instead of using adaptor pattern to wrap `REPL.Terminal.TTYTerminal`
